### ISSUE TITLE
Option 'emitDeclarationOnly' cannot be specified without specifying option 'declaration' or option 'composite'.

### ISSUE THREAD

**Issue by NukeJS** [LyonInc/pridepack#16]
I keep getting the error "Option 'emitDeclarationOnly' cannot be specified without specifying option 'declaration' or option 'composite'."

Even though I don't use `emitDeclarationOnly` in my tsconfig.json file.

**Comment by LXSMNSYC** [comment]
`emitDeclarationOnly` is actually only used in `pridepack` for the TS compilation and d.ts output.

I'll check out what `composite` refers to

**Comment by NukeJS** [comment]
I think I know what the issue is.

I have a monorepo with a parent `tsconfig.json` and a child `tsconfig.json`, this is located in `packages/solidjs-hooks`. In the child config file I had only provided a `extends` property to let typescript know i want to extend the parent config file, I never declared any other `compilerOptions` inside the child config file. It seems like pridepack doesn't resolve the `extends` property, it tries to directly read the child config file's own `compilerOptions`.
