### ISSUE TITLE
LICENSE file not generated on init

### ISSUE THREAD

**Issue by TheoryOfNekomata** [LyonInc/pridepack#8]
License file is not present as soon as I generated a project. I suggest to use the Git username like TSDX does.

**Comment by LXSMNSYC** [comment]
I've considered this before, however I decided to delegate this problem on `yarn init`

I'm still unsure if I should integrate it.

**Comment by LXSMNSYC** [comment]
I'll be adding this for the terminal UI rewrite

**Comment by LXSMNSYC** [comment]
Added on the next release
